[pytest]
# Wskazuję pytestowi, gdzie znajdują się główne ustawienia mojego projektu
DJANGO_SETTINGS_MODULE = core.settings
# Określam, w jakich plikach pytest ma szukać testów
python_files = tests.py test_*.py *_tests.py