# Generated by Django 6.0.8 on 2026-08-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(choices=[('CERT', 'CERT Polska'), ('CSIRT', 'CSIRT GOV'), ('Niebezpiecznik', 'Niebezpiecznik'), ('OTHER', 'Inne')], default='OTHER', max_length=50, verbose_name='Źródło'),
        ),
    ]
