"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.8.
"""

import environ
from pathlib import Path

# Buduję ścieżki wewnątrz projektu: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicjalizuję bibliotekę do obsługi zmiennych środowiskowych
env = environ.Env()

# Wczytuję ukryte hasła z pliku .env, który musi znajdować się w głównym folderze mojego projektu
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
# Pobieram klucz szyfrujący z pliku .env
SECRET_KEY = env('SECRET_KEY', default='bezpieczny-klucz-zapasowy')

# SECURITY WARNING: don't run with debug turned on in production!
# Pobieram status DEBUG, domyślnie wyłączam dla bezpieczeństwa (False)
DEBUG = env.bool('DEBUG', default=False)

# Pozwalam na dostęp do mojego serwera z dowolnego adresu w środowisku lokalnym
ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Rejestruję framework do budowy API oraz moją nową aplikację
    'rest_framework',
    'rest_framework_simplejwt', # Dodaję bibliotekę do obsługi tokenów JWT
    'django.contrib.postgres',  # Dodaję wtyczkę PostgreSQL do obsługi full-text search
    'drf_spectacular',          # Dodaję bibliotekę do automatycznego generowania dokumentacji Swagger/OpenAPI
    'news',
]

# Konfiguruję DRF, aby domyślnie używał tokenów JWT oraz automatycznego generatora schematów
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Konfiguruję metadane i nagłówki dla generowanej dokumentacji API
SPECTACULAR_SETTINGS = {
    'TITLE': 'Agregator Zagrożeń API',
    'DESCRIPTION': 'Oficjalny interfejs programistyczny systemu agregacji cyberzagrożeń.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# Konfiguruję połączenie z moją nową bazą PostgreSQL z wykorzystaniem zmiennych z pliku .env
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB', default='agregator_db'),
        'USER': env('POSTGRES_USER', default='bg_user'),
        'PASSWORD': env('POSTGRES_PASSWORD', default='secret_password'),
        'HOST': env('POSTGRES_HOST', default='db'),
        'PORT': env('POSTGRES_PORT', default='5432'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'


# CELERY & REDIS CONFIGURATION
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Warsaw'

from celery.schedules import crontab

# HARMONOGRAM ZADAŃ (CELERY BEAT)
CELERY_BEAT_SCHEDULE = {
    'pobieranie-nowych-zagrozen-co-godzine': {
        'task': 'news.tasks.fetch_new_articles',
        'schedule': crontab(minute=0), 
    },
}

# Mówię Django, że od teraz autoryzacja ma opierać się na moim nowym modelu User
AUTH_USER_MODEL = 'news.User'

# Przekierowanie po pomyślnym zalogowaniu
LOGIN_REDIRECT_URL = 'dashboard'

# Przekierowanie po wylogowaniu
LOGOUT_REDIRECT_URL = 'home'

# Bezpieczeństwo CSRF dla środowiska lokalnego/Docker
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
CSRF_COOKIE_SECURE = False  # Pozwala na przesyłanie tokena po zwykłym HTTP (bez HTTPS)
SESSION_COOKIE_SECURE = False


# EMAIL CONFIGURATION
# Na potrzeby deweloperskie wymuszam wypisywanie emaili bezpośrednio w terminalu (konsoli)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'agregator@sg.gov.pl'